model_list:
  - model_name: "anthropic/*"
    litellm_params:
      model: "openai/glm47-flash"
      api_base: "http://vllm-node:8000/v1"
      api_key: "sk-FAKE"
      max_tokens: 65536
      repetition_penalty: 1.05
      temperature: 0.7
      top_k: 20
      top_p: 0.8
