#!/bin/bash
#
# Build a runtime models.yml from per-model fragments in /app/models.
# If MODEL is set, only that model fragment is included in the generated file.
#

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="${MODELS_DIR:-${SCRIPT_DIR}/../models}"
OUTPUT_FILE="${MODELS_YML_PATH:-/app/generated_configs/models.yml}"
MODEL_NAME="${MODEL_NAME:-${MODEL:-}}"
VARIANT_NAME="${VARIANT_NAME:-${VARIANT:-}}"

info() { echo "[INFO] $1"; }
err()  { echo "[ERROR] $1" >&2; }

usage() {
    cat <<USAGE
Generate models.yml from per-model fragments.

Env Vars:
  MODELS_DIR            Directory containing model fragments (*.yml)
  MODELS_YML_PATH       Output file path (default: /app/generated_configs/models.yml)
  MODEL / MODEL_NAME    Optional selected model key (e.g. glm47-flash)
  VARIANT / VARIANT_NAME  Optional variant for family model files (e.g. nvfp4)

Options:
  --model NAME     Same as MODEL_NAME env var
  --variant NAME   Same as VARIANT_NAME env var
  --dry-run        Show selected inputs and output path without writing
  --help, -h       Show this help
USAGE
}

validate_readable_file() {
    local path="$1"
    [[ -f "$path" ]] || { err "Not a file: $path"; return 1; }
    [[ -r "$path" ]] || { err "Not readable: $path"; return 1; }
    return 0
}

collect_model_names() {
    local discovered
    discovered="$(find "$MODELS_DIR" -maxdepth 1 -type f -name "*.yml" -printf "%f\n" \
        | sed -E 's/\.yml$//' \
        | grep -v '\-base$' \
        | sort)"

    if [[ -n "$MODEL_NAME" ]]; then
        if [[ ! -f "${MODELS_DIR}/${MODEL_NAME}.yml" ]]; then
            err "Requested model '${MODEL_NAME}' not found in ${MODELS_DIR}"
            if [[ -n "$discovered" ]]; then
                err "Available models: $(echo "$discovered" | tr '\n' ' ')"
            fi
            return 1
        fi
        echo "$MODEL_NAME"
        return 0
    fi

    echo "$discovered"
}

append_model_block() {
    local model="$1"
    local source_file="${MODELS_DIR}/${model}.yml"
    validate_readable_file "$source_file" || return 1

    printf "%s:\n" "$model" >> "$OUTPUT_FILE"

    if grep -q '^variants:' "$source_file" 2>/dev/null; then
        # Family file: Python resolver handles defaults + variant merge
        python3 "${SCRIPT_DIR}/resolve_variant.py" \
            --models-dir "$MODELS_DIR" \
            --model "$model" \
            ${VARIANT_NAME:+--variant "$VARIANT_NAME"} \
            | sed 's/^/  /' >> "$OUTPUT_FILE"
    else
        # Legacy flat file: strip document markers and indent
        sed '/^---$/d' "$source_file" | sed 's/^/  /' >> "$OUTPUT_FILE"
    fi

    printf "\n" >> "$OUTPUT_FILE"
}

generate_models_yml() {
    local target_dir
    target_dir="$(dirname "$OUTPUT_FILE")"
    mkdir -p "$target_dir"

    cat > "$OUTPUT_FILE" <<EOF
---
# AUTOGENERATED: models.yml
# Source directory: $MODELS_DIR
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

EOF

    local selected_models
    if ! selected_models="$(collect_model_names)"; then
        return 1
    fi

    local model_count=0
    while IFS= read -r model; do
        [[ -z "$model" ]] && continue
        append_model_block "$model"
        model_count=$((model_count + 1))
    done <<< "$selected_models"

    if [[ "$model_count" -eq 0 ]]; then
        err "No model fragments found in $MODELS_DIR"
        return 1
    fi

    info "Generated $OUTPUT_FILE with $model_count model(s)"
}

DRY_RUN=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --model)
            shift
            [[ $# -gt 0 ]] || { err "Missing value for --model"; usage; exit 1; }
            MODEL_NAME="$1"
            ;;
        --variant)
            shift
            [[ $# -gt 0 ]] || { err "Missing value for --variant"; usage; exit 1; }
            VARIANT_NAME="$1"
            ;;
        --dry-run)
            DRY_RUN=1
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            err "Unknown arg: $1"
            usage
            exit 1
            ;;
    esac
    shift
done

[[ -d "$MODELS_DIR" ]] || { err "Missing models dir: $MODELS_DIR"; exit 1; }

if [[ "$DRY_RUN" -eq 1 ]]; then
    info "[DRY RUN] MODELS_DIR=$MODELS_DIR"
    info "[DRY RUN] OUTPUT_FILE=$OUTPUT_FILE"
    info "[DRY RUN] MODEL_NAME=${MODEL_NAME:-<all>}"
    info "[DRY RUN] VARIANT_NAME=${VARIANT_NAME:-<none>}"
    while IFS= read -r model; do
        [[ -n "$model" ]] && echo "  - ${MODELS_DIR}/${model}.yml"
    done < <(collect_model_names)
    exit 0
fi

generate_models_yml
