services:
  vllm-node:
    image: scitrera/dgx-spark-vllm:0.14.0-t5
    container_name: vllm-container
    restart: unless-stopped

    ports:
      - "8000:8000"

    gpus: all

    env_file:
      - ./env

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface

    command: >
      vllm serve QuantTrio/GLM-4.7-Flash-AWQ
      --port 8000
      --host 0.0.0.0
      --api-key ${OPENAI_API_KEY}
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.93
      --max-model-len 128000
      --trust-remote-code
      --tool-call-parser glm47
      --reasoning-parser glm45
      --enable-auto-tool-choice
      --served-model-name QuantTrio/GLM-4.7-Flash-AWQ

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    command: ["--config=/app/config.yaml"]
    container_name: litellm
    restart: unless-stopped

    volumes:
      - ./config.yml:/app/config.yaml

    ports:
      - "4000:4000"

    env_file:
      - ./env

    depends_on:
      db:
        condition: service_healthy
      vllm-node:
        condition: service_started

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    restart: always
    container_name: litellm_db

    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090

    # No ports: internal only

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: litellm_postgres_data
